spring.application.name=stats-server
server.port=9090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6541/stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.show-sql=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC